services:
  postgres:
    image: postgis/postgis:10-2.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql postgresql://postgres@:5432/postgres -c 'select 1;'" ]
      interval: 10s
      timeout: 3s
      retries: 15

  liquibase-users:
    image: liquibase/liquibase:4.6.2
    container_name: liquibase-users
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./databases/ku-users:/databases/ku-users
    command: >
      liquibase
        --logLevel=INFO
        --driver=org.postgresql.Driver
        --classpath="/databases/ku-users/"
        --changeLogFile="changelog.xml"
        --url="jdbc:postgresql://postgres:5432/postgres"
        --username=postgres
        --password=postgres
      update